In [0]:
# Generating multiple sequences
import numpy as np

in_seq_1 = []
in_seq_2 = []
in_seq_3 = []

for i in range(1, 1001):
    in_seq_1.append(i*10)
    in_seq_2.append(i*10)
    in_seq_3.append(i*20)
    
in_seq_1 = np.array(in_seq_1)
in_seq_2 = np.array(in_seq_2)
in_seq_3 = np.array(in_seq_3)

In [0]:
# Convert to [rows, columns] structure
in_seq_1 = in_seq_1.reshape(in_seq_1.shape[0], 1)
in_seq_2 = in_seq_2.reshape(in_seq_2.shape[0], 1)
in_seq_3 = in_seq_3.reshape(in_seq_3.shape[0], 1)

# Horizontally stack columns
dataset = np.hstack((in_seq_1, in_seq_2, in_seq_3))

In [4]:
dataset

array([[   10,    10,    20],
       [   20,    20,    40],
       [   30,    30,    60],
       ...,
       [ 9980,  9980, 19960],
       [ 9990,  9990, 19980],
       [10000, 10000, 20000]])

In [0]:
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        end_ix = i + n_steps
        if end_ix > len(sequences) - 1:
            break
            
        seq_x, seq_y = sequences[i:end_ix, :], sequences[end_ix, :]
        X.append(seq_x)
        y.append(seq_y)
        
    return np.array(X), np.array(y)

In [15]:
n_steps = 3
X, y = split_sequences(dataset, n_steps)

for i in range(len(X)):
    print(X[i], y[i])

[[10 10 20]
 [20 20 40]
 [30 30 60]] [40 40 80]
[[20 20 40]
 [30 30 60]
 [40 40 80]] [ 50  50 100]
[[ 30  30  60]
 [ 40  40  80]
 [ 50  50 100]] [ 60  60 120]
[[ 40  40  80]
 [ 50  50 100]
 [ 60  60 120]] [ 70  70 140]
[[ 50  50 100]
 [ 60  60 120]
 [ 70  70 140]] [ 80  80 160]
[[ 60  60 120]
 [ 70  70 140]
 [ 80  80 160]] [ 90  90 180]
[[ 70  70 140]
 [ 80  80 160]
 [ 90  90 180]] [100 100 200]
[[ 80  80 160]
 [ 90  90 180]
 [100 100 200]] [110 110 220]
[[ 90  90 180]
 [100 100 200]
 [110 110 220]] [120 120 240]
[[100 100 200]
 [110 110 220]
 [120 120 240]] [130 130 260]
[[110 110 220]
 [120 120 240]
 [130 130 260]] [140 140 280]
[[120 120 240]
 [130 130 260]
 [140 140 280]] [150 150 300]
[[130 130 260]
 [140 140 280]
 [150 150 300]] [160 160 320]
[[140 140 280]
 [150 150 300]
 [160 160 320]] [170 170 340]
[[150 150 300]
 [160 160 320]
 [170 170 340]] [180 180 360]
[[160 160 320]
 [170 170 340]
 [180 180 360]] [190 190 380]
[[170 170 340]
 [180 180 360]
 [190 190 380]] [200 200 400]
[

In [16]:
X

array([[[   10,    10,    20],
        [   20,    20,    40],
        [   30,    30,    60]],

       [[   20,    20,    40],
        [   30,    30,    60],
        [   40,    40,    80]],

       [[   30,    30,    60],
        [   40,    40,    80],
        [   50,    50,   100]],

       ...,

       [[ 9950,  9950, 19900],
        [ 9960,  9960, 19920],
        [ 9970,  9970, 19940]],

       [[ 9960,  9960, 19920],
        [ 9970,  9970, 19940],
        [ 9980,  9980, 19960]],

       [[ 9970,  9970, 19940],
        [ 9980,  9980, 19960],
        [ 9990,  9990, 19980]]])

In [7]:
n_features = X.shape[2]
print(n_features)

3


In [8]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

Using TensorFlow backend.


In [9]:
model = Sequential()
model.add(LSTM(100, activation = "relu", return_sequences = True, input_shape = (n_steps, n_features)))
model.add(LSTM(100, activation = "relu"))
model.add(Dense(n_features))

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
model.compile(optimizer = "adam", loss = "mse")

In [13]:
model.fit(X, y, epochs = 400, batch_size = 10, shuffle = True, verbose = 1)

Epoch 1/400
997/997 [==============================] - 2s 2ms/step - loss: 6.2509
Epoch 2/400
997/997 [==============================] - 2s 2ms/step - loss: 0.9180
Epoch 3/400
997/997 [==============================] - 2s 2ms/step - loss: 0.6489
Epoch 4/400
997/997 [==============================] - 2s 2ms/step - loss: 0.4435
Epoch 5/400
997/997 [==============================] - 2s 2ms/step - loss: 0.3188
Epoch 6/400
997/997 [==============================] - 2s 2ms/step - loss: 0.2050
Epoch 7/400
997/997 [==============================] - 2s 2ms/step - loss: 0.1114
Epoch 8/400
997/997 [==============================] - 2s 2ms/step - loss: 0.0281
Epoch 9/400
997/997 [==============================] - 2s 2ms/step - loss: 0.0205
Epoch 10/400
997/997 [==============================] - 2s 2ms/step - loss: 0.0166
Epoch 11/400
997/997 [==============================] - 2s 2ms/step - loss: 0.0123
Epoch 12/400
997/997 [==============================] - 2s 2ms/step - loss: 0.0078
Epoch 13/400


Epoch 1/400
997/997 [==============================] - 2s 2ms/step - loss: 7.3706e-05
Epoch 2/400
997/997 [==============================] - 2s 2ms/step - loss: 6.4647e-05
Epoch 3/400
997/997 [==============================] - 2s 2ms/step - loss: 4.2313e-05
Epoch 4/400
997/997 [==============================] - 2s 2ms/step - loss: 3.1100e-05
Epoch 5/400
997/997 [==============================] - 2s 2ms/step - loss: 1.0584e-04
Epoch 6/400
997/997 [==============================] - 2s 2ms/step - loss: 4.4739e-05
Epoch 7/400
997/997 [==============================] - 2s 2ms/step - loss: 2.8192e-04
Epoch 8/400
997/997 [==============================] - 2s 2ms/step - loss: 1.1147e-04
Epoch 9/400
997/997 [==============================] - 2s 2ms/step - loss: 5.6890e-05
Epoch 10/400
997/997 [==============================] - 2s 2ms/step - loss: 4.7136e-04
Epoch 11/400
997/997 [==============================] - 2s 2ms/step - loss: 0.0465
Epoch 12/400
997/997 [==============================] - 

In [20]:
test_input = np.array([[100, 100, 200], [110, 110, 220], [120, 120, 240]])
test_input = test_input.reshape(1, n_steps, n_features)
model.predict(test_input, verbose = 0)

array([[129.96295, 129.9519 , 260.02216]], dtype=float32)

In [22]:
y_pred = model.predict(X, verbose = 1)

997/997 [==============================] - 0s 217us/step


In [37]:
for i in range(len(y_pred)):
    print(y[i])
    print(y_pred[i])
    print("-------------------")

[40 40 80]
[40.070744 40.097282 79.98127 ]
-------------------
[ 50  50 100]
[ 50.03872  50.08085 100.01061]
-------------------
[ 60  60 120]
[ 59.988987  60.052727 120.02801 ]
-------------------
[ 70  70 140]
[ 69.88287  70.00803 140.03128]
-------------------
[ 80  80 160]
[ 79.8365    79.949356 160.00969 ]
-------------------
[ 90  90 180]
[ 89.90121  89.91143 180.01054]
-------------------
[100 100 200]
[ 99.93008  99.91742 200.02274]
-------------------
[110 110 220]
[109.94103 109.92891 220.02254]
-------------------
[120 120 240]
[119.95198 119.94043 240.02235]
-------------------
[130 130 260]
[129.96295 129.9519  260.02216]
-------------------
[140 140 280]
[139.97389 139.96341 280.0219 ]
-------------------
[150 150 300]
[149.98486 149.9749  300.02176]
-------------------
[160 160 320]
[159.99583 159.9864  320.02155]
-------------------
[170 170 340]
[170.00676 169.9979  340.0213 ]
-------------------
[180 180 360]
[180.01772 180.00938 360.02112]
-------------------
[190 19

In [19]:
100 - model.evaluate(X, y, verbose = 1)*100

997/997 [==============================] - 0s 238us/step


96.53424735824646