In [0]:
# Generating multiple sequence
import numpy as np
in_seq_1 = []
in_seq_2 = []

for i in range(1, 1001):
    in_seq_1.append(i*10 + 2)
    in_seq_2.append(i*10 + 3)
    
in_seq_1 = np.array(in_seq_1)
in_seq_2 = np.array(in_seq_2)
out_seq = np.array([in_seq_1[i] + in_seq_2[i] for i in range(len(in_seq_1))])

In [2]:
print(in_seq_1)
print(in_seq_2)
print(out_seq)

[   12    22    32    42    52    62    72    82    92   102   112   122
   132   142   152   162   172   182   192   202   212   222   232   242
   252   262   272   282   292   302   312   322   332   342   352   362
   372   382   392   402   412   422   432   442   452   462   472   482
   492   502   512   522   532   542   552   562   572   582   592   602
   612   622   632   642   652   662   672   682   692   702   712   722
   732   742   752   762   772   782   792   802   812   822   832   842
   852   862   872   882   892   902   912   922   932   942   952   962
   972   982   992  1002  1012  1022  1032  1042  1052  1062  1072  1082
  1092  1102  1112  1122  1132  1142  1152  1162  1172  1182  1192  1202
  1212  1222  1232  1242  1252  1262  1272  1282  1292  1302  1312  1322
  1332  1342  1352  1362  1372  1382  1392  1402  1412  1422  1432  1442
  1452  1462  1472  1482  1492  1502  1512  1522  1532  1542  1552  1562
  1572  1582  1592  1602  1612  1622  1632  1642  1

In [0]:
# Convert to [rows, columns] structure
in_seq_1 = in_seq_1.reshape(in_seq_1.shape[0], 1)
in_seq_2 = in_seq_2.reshape(in_seq_2.shape[0], 1)
out_seq = out_seq.reshape(out_seq.shape[0], 1)

# Horizontally stack columns
dataset = np.hstack((in_seq_1, in_seq_2, out_seq))

In [6]:
print(dataset)

[[   12    13    25]
 [   22    23    45]
 [   32    33    65]
 ...
 [ 9982  9983 19965]
 [ 9992  9993 19985]
 [10002 10003 20005]]


In [0]:
def split_sequences(sequences, n_steps):
    X, y = list(), list()
    for i in range(len(sequences)):
        end_ix = i + n_steps
        if(end_ix) > len(sequences) - 1:
            break
        
        seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [12]:
n_steps = 3
X, y = split_sequences(dataset, n_steps)

for i in range(len(X)):
    print(X[i], y[i])

[[12 13]
 [22 23]
 [32 33]] 65
[[22 23]
 [32 33]
 [42 43]] 85
[[32 33]
 [42 43]
 [52 53]] 105
[[42 43]
 [52 53]
 [62 63]] 125
[[52 53]
 [62 63]
 [72 73]] 145
[[62 63]
 [72 73]
 [82 83]] 165
[[72 73]
 [82 83]
 [92 93]] 185
[[ 82  83]
 [ 92  93]
 [102 103]] 205
[[ 92  93]
 [102 103]
 [112 113]] 225
[[102 103]
 [112 113]
 [122 123]] 245
[[112 113]
 [122 123]
 [132 133]] 265
[[122 123]
 [132 133]
 [142 143]] 285
[[132 133]
 [142 143]
 [152 153]] 305
[[142 143]
 [152 153]
 [162 163]] 325
[[152 153]
 [162 163]
 [172 173]] 345
[[162 163]
 [172 173]
 [182 183]] 365
[[172 173]
 [182 183]
 [192 193]] 385
[[182 183]
 [192 193]
 [202 203]] 405
[[192 193]
 [202 203]
 [212 213]] 425
[[202 203]
 [212 213]
 [222 223]] 445
[[212 213]
 [222 223]
 [232 233]] 465
[[222 223]
 [232 233]
 [242 243]] 485
[[232 233]
 [242 243]
 [252 253]] 505
[[242 243]
 [252 253]
 [262 263]] 525
[[252 253]
 [262 263]
 [272 273]] 545
[[262 263]
 [272 273]
 [282 283]] 565
[[272 273]
 [282 283]
 [292 293]] 585
[[282 283]
 [292 2

In [13]:
n_features = X.shape[2]
print(n_features)

2


In [14]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

Using TensorFlow backend.


In [15]:
model = Sequential()
model.add(LSTM(50, activation = "relu", input_shape = (n_steps, n_features)))
model.add(Dense(1))

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
model.compile(optimizer = "adam", loss = "mse")

In [17]:
model.fit(X, y, epochs = 200, verbose = 0)

Instructions for updating:
Use tf.cast instead.


In [22]:
test_input = np.array([[19, 21], [29, 31], [39, 41]])
test_input = test_input.reshape(1, n_steps, n_features)
model.predict(test_input, verbose = 0)

array([[80.55432]], dtype=float32)

In [0]:
# https://keras.io/getting-started/faq/#how-can-i-save-a-keras-model
model.save("multivariate-multi-input-lstm.h5")

In [24]:
pwd

'/content'

In [25]:
import os
for root, dirs, files in os.walk("/content"):
    for file in files:
        print(file)

multivariate-multi-input-lstm.h5
config_sentinel
active_config
gce
.last_update_check.json
17.25.47.445682.log
17.25.39.666145.log
17.25.50.927546.log
17.25.35.577705.log
17.25.50.161939.log
config_default
README.md
anscombe.json
mnist_test.csv
california_housing_test.csv
california_housing_train.csv
mnist_train_small.csv
