In [3]:
# Lets generate a sequence to act as our dataset
# In our sequence the next number will be 10 greater than the previous one

raw_seq = []
for i in range(1, 10001):
    raw_seq.append(i*10)
    
print(raw_seq)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830, 840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990, 1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090, 1100, 1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 1190, 1200, 1210, 1220, 1230, 1240, 1250, 1260, 1270, 1280, 1290, 1300, 1310, 1320, 1330, 1340, 1350, 1360, 1370, 1380, 1390, 1400, 1410, 1420, 1430, 1440, 1450, 1460, 1470, 1480, 1490, 1500, 1510, 1520, 1530, 1540, 1550, 1560, 1570, 1580, 1590, 1600, 1610, 1620, 1630, 1640, 1650, 1660, 1670, 1680, 1690, 1700, 1710, 1720, 1730, 1740, 1750, 1760, 1770, 1780, 1790, 1800, 1810, 1820, 1830, 1840, 185

In [0]:
# Split the sequence to features and label
# Each sequence has a specified number of input time steps and one output time step
import numpy as np

def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        end_ix = i + n_steps
        if(end_ix) > len(sequence) - 1:
            break
        
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

In [8]:
split_sequence([1, 2, 3, 4, 5, 6], 2)

(array([[1, 2],
        [2, 3],
        [3, 4],
        [4, 5]]), array([3, 4, 5, 6]))

In [10]:
n_steps = 3
X, y = split_sequence(raw_seq, n_steps)

for i in range(len(X)):
    print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90
[70 80 90] 100
[ 80  90 100] 110
[ 90 100 110] 120
[100 110 120] 130
[110 120 130] 140
[120 130 140] 150
[130 140 150] 160
[140 150 160] 170
[150 160 170] 180
[160 170 180] 190
[170 180 190] 200
[180 190 200] 210
[190 200 210] 220
[200 210 220] 230
[210 220 230] 240
[220 230 240] 250
[230 240 250] 260
[240 250 260] 270
[250 260 270] 280
[260 270 280] 290
[270 280 290] 300
[280 290 300] 310
[290 300 310] 320
[300 310 320] 330
[310 320 330] 340
[320 330 340] 350
[330 340 350] 360
[340 350 360] 370
[350 360 370] 380
[360 370 380] 390
[370 380 390] 400
[380 390 400] 410
[390 400 410] 420
[400 410 420] 430
[410 420 430] 440
[420 430 440] 450
[430 440 450] 460
[440 450 460] 470
[450 460 470] 480
[460 470 480] 490
[470 480 490] 500
[480 490 500] 510
[490 500 510] 520
[500 510 520] 530
[510 520 530] 540
[520 530 540] 550
[530 540 550] 560
[540 550 560] 570
[550 560 570] 580
[560 570 580] 590
[570 580 590] 600
[

In [14]:
# Reshape X from [samples, timesteps] to [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
X

array([[[   10],
        [   20],
        [   30]],

       [[   20],
        [   30],
        [   40]],

       [[   30],
        [   40],
        [   50]],

       ...,

       [[99950],
        [99960],
        [99970]],

       [[99960],
        [99970],
        [99980]],

       [[99970],
        [99980],
        [99990]]])

In [0]:
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense

In [15]:
model = Sequential()
model.add(LSTM(50, activation = "relu", input_shape = (n_steps, n_features)))
model.add(Dense(1))

Instructions for updating:
Colocations handled automatically by placer.


In [0]:
model.compile(optimizer = "adam", loss = "mse")

In [19]:
model.fit(X, y, epochs = 200, verbose = 0)

Instructions for updating:
Use tf.cast instead.


In [23]:
test_input = np.array([15, 25, 35])
test_input = test_input.reshape(1, n_steps, n_features)
model.predict(test_input, verbose = 0)

array([[46.19129]], dtype=float32)