# Getting started with tensorflow

## Getting to know the tensorflow version

In [0]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.13.1


In [0]:
hello_world = tf.constant("Hello, World!")

In [0]:
sess = tf.Session()

In [9]:
print(sess.run(hello_world))

b'Hello, World!'


## Creating first simplest tensor

In [0]:
hello = tf.constant("Hello, ")

In [0]:
world = tf.constant("World!")

In [12]:
type(hello)

tensorflow.python.framework.ops.Tensor

## Creating a tensorflow session

In [0]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [14]:
print(result)

b'Hello, World!'


## First addition operation

In [0]:
a = tf.constant(10)
b = tf.constant(20)

In [16]:
type(a)

tensorflow.python.framework.ops.Tensor

In [17]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [18]:
a + b

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [0]:
with tf.Session() as sess:
    result = sess.run(a + b)

In [20]:
print(result)

30


## Creating first matrix

In [0]:
const = tf.constant(10)

In [0]:
# Creating a 4x4 matrix
fill_mat = tf.fill((4, 4), 10)

In [0]:
myzeros = tf.zeros((4, 4))

In [0]:
myones = tf.ones((4, 4))

In [0]:
myrand_normal = tf.random_normal((4, 4), mean = 0, stddev = 1.0)

In [0]:
myrand_uniform = tf.random_uniform((4, 4), minval = 0, maxval = 1)

In [29]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [0]:
my_ops = [const, fill_mat, myzeros, myones, myrand_normal, myrand_uniform]

## Using Interactive Session for Jupyter Notebooks

In [37]:
sess = tf.InteractiveSession() # Only usable with the jupyter notebook

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py:1702: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [38]:
for op in my_ops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 3.5866672e-01  2.0891917e-01 -2.0945109e-01 -5.5659690e-04]
 [-2.1506605e-01 -1.2665357e-01 -6.6412526e-01  2.8643582e+00]
 [-1.7493166e+00 -2.4143569e+00 -2.2804090e-01  4.8741028e-01]
 [ 6.8123925e-01 -1.9103670e+00  7.2341084e-02  6.3516212e-01]]


[[0.7589328  0.11129498 0.12968099 0.08444715]
 [0.97991264 0.16399789 0.3875357  0.17902505]
 [0.7071713  0.80917645 0.18107986 0.26161098]
 [0.14840424 0.61074317 0.17285013 0.4164511 ]]




## Working with matrix

In [0]:
a = tf.constant([
    [1,2],
    [3,4]
])

In [41]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [0]:
b = tf.constant([
    [10],
    [20]
])

In [43]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [0]:
result = tf.matmul(a, b)

In [45]:
sess.run(result)

array([[ 50],
       [110]], dtype=int32)